name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Android NDK
      uses: reactivecircus/android-emulator-runner@v2
      env:
        # Make sure to set the correct path according to your NDK location.
        ANDROID_NDK_HOME: ${{ runner.home }}/android-sdk/ndk/25.2.9
        

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: upload result
      uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk
      
